Text:
  label_title: 基于YOLOv5的疲劳驾驶检测系统
  label_website_2: 知乎：思绪无限
  label_author: B站：思绪亦无限
  label_website: wuxian.blog.csdn.net
  label_time_result: 0 s
  label_numer_result: '0'
  label_class_result: '0'
  label_score_result: '0'
  label_xmin_result: '0'
  label_ymin_result: '0'
  label_xmax_result: '0'
  label_ymax_result: '0'
  textEdit_pic: 选择图片文件
  textEdit_video: 选择视频文件
  textEdit_camera: 摄像头未开启
Icon:
  windowIcon: ./icons/sign.png
  mainWindow: ./icons/back-image.png
  toolButton_saveing: ./icons/save.png
  toolButton_settings: ./icons/settings.png
  toolButton_author: ./icons/author.png
  toolButton_version: ./icons/versions.png
  toolButton_file: ./icons/recovery.png
  toolButton_video: ./icons/video.png
  toolButton_camera: ./icons/g1.png
  toolButton_model: ./icons/model.png
  toolButton_folder: ./icons/folder.png
  label_picTime: ./icons/net_speed.png
  label_picNumber: ./icons/count.png
  label_picSelect: ./icons/selection.png
  label_picResult: ./icons/result.png
  label_picConf: ./icons/Score.png
  label_picLocation: ./icons/Ordinateur.png
  label_display: ./icons/ini-image.png
